package test.model.entity;
// Generated 2018/2/4 ¤U¤È 03:34:56 by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InventoryTransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "inventory_transaction_types", catalog = "northwind")
public class InventoryTransactionTypes implements java.io.Serializable {

	private byte id;
	private String typeName;
	private Set<InventoryTransactions> inventoryTransactionses = new HashSet<InventoryTransactions>(0);

	public InventoryTransactionTypes() {
	}

	public InventoryTransactionTypes(byte id, String typeName) {
		this.id = id;
		this.typeName = typeName;
	}

	public InventoryTransactionTypes(byte id, String typeName, Set<InventoryTransactions> inventoryTransactionses) {
		this.id = id;
		this.typeName = typeName;
		this.inventoryTransactionses = inventoryTransactionses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "type_name", nullable = false, length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventoryTransactionTypes")
	public Set<InventoryTransactions> getInventoryTransactionses() {
		return this.inventoryTransactionses;
	}

	public void setInventoryTransactionses(Set<InventoryTransactions> inventoryTransactionses) {
		this.inventoryTransactionses = inventoryTransactionses;
	}

}
