package test.model.entity;
// Generated 2018/2/4 ¤U¤È 03:34:56 by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PurchaseOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "purchase_order_status", catalog = "northwind")
public class PurchaseOrderStatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set<PurchaseOrders> purchaseOrderses = new HashSet<PurchaseOrders>(0);

	public PurchaseOrderStatus() {
	}

	public PurchaseOrderStatus(int id) {
		this.id = id;
	}

	public PurchaseOrderStatus(int id, String status, Set<PurchaseOrders> purchaseOrderses) {
		this.id = id;
		this.status = status;
		this.purchaseOrderses = purchaseOrderses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseOrderStatus")
	public Set<PurchaseOrders> getPurchaseOrderses() {
		return this.purchaseOrderses;
	}

	public void setPurchaseOrderses(Set<PurchaseOrders> purchaseOrderses) {
		this.purchaseOrderses = purchaseOrderses;
	}

}
