package test.model.entity;
// Generated 2018/2/4 ¤U¤È 03:34:56 by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalesReports generated by hbm2java
 */
@Entity
@Table(name = "sales_reports", catalog = "northwind")
public class SalesReports implements java.io.Serializable {

	private String groupBy;
	private String display;
	private String title;
	private String filterRowSource;
	private boolean default_;

	public SalesReports() {
	}

	public SalesReports(String groupBy, boolean default_) {
		this.groupBy = groupBy;
		this.default_ = default_;
	}

	public SalesReports(String groupBy, String display, String title, String filterRowSource, boolean default_) {
		this.groupBy = groupBy;
		this.display = display;
		this.title = title;
		this.filterRowSource = filterRowSource;
		this.default_ = default_;
	}

	@Id

	@Column(name = "group_by", unique = true, nullable = false, length = 50)
	public String getGroupBy() {
		return this.groupBy;
	}

	public void setGroupBy(String groupBy) {
		this.groupBy = groupBy;
	}

	@Column(name = "display", length = 50)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "filter_row_source")
	public String getFilterRowSource() {
		return this.filterRowSource;
	}

	public void setFilterRowSource(String filterRowSource) {
		this.filterRowSource = filterRowSource;
	}

	@Column(name = "default", nullable = false)
	public boolean isDefault_() {
		return this.default_;
	}

	public void setDefault_(boolean default_) {
		this.default_ = default_;
	}

}
